import { db } from "./__client";
import * as schema from "./schema";

const img = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1400&q=80`;

const data: (typeof schema.properties.$inferInsert)[] = [
  {
    title: "Cobertura Duplex com Vista Panorâmica",
    purpose: "venda",
    type: "cobertura",
    price: 4850000,
    city: "São Paulo",
    neighborhood: "Jardins",
    state: "SP",
    bedrooms: 4,
    suites: 4,
    bathrooms: 5,
    parking: 4,
    area: 380,
    reference: "HM-1001",
    featured: true,
    description:
      "Cobertura duplex assinada por arquitetura premiada, com terraço gourmet, piscina privativa e vista aberta para a cidade. Acabamentos em mármore e madeira nobre, automação completa e pé-direito duplo na sala de estar.",
    images: [
      img("photo-1613490493576-7fde63acd811"),
      img("photo-1600607687939-ce8a6c25118c"),
      img("photo-1600566753086-00f18fb6b3ea"),
      img("photo-1600210492486-724fe5c67fb0"),
    ],
    features: ["Piscina privativa", "Terraço gourmet", "Automação", "Vista panorâmica", "Adega climatizada"],
  },
  {
    title: "Casa Contemporânea em Condomínio Fechado",
    purpose: "venda",
    type: "casa",
    price: 3200000,
    city: "São Paulo",
    neighborhood: "Alphaville",
    state: "SP",
    bedrooms: 4,
    suites: 3,
    bathrooms: 4,
    parking: 4,
    area: 420,
    reference: "HM-1002",
    featured: true,
    description:
      "Residência de linhas contemporâneas em condomínio de alto padrão, com amplo jardim, piscina com raia e integração total entre áreas internas e externas. Segurança 24h e clube completo.",
    images: [
      img("photo-1600585154340-be6161a56a0c"),
      img("photo-1600566753190-17f0baa2a6c3"),
      img("photo-1600585154526-990dced4db0d"),
      img("photo-1600047509807-ba8f99d2cdde"),
    ],
    features: ["Condomínio fechado", "Piscina", "Jardim", "Segurança 24h", "Espaço gourmet"],
  },
  {
    title: "Apartamento de Alto Padrão com Varanda Integrada",
    purpose: "venda",
    type: "apartamento",
    price: 2150000,
    city: "São Paulo",
    neighborhood: "Vila Nova Conceição",
    state: "SP",
    bedrooms: 3,
    suites: 3,
    bathrooms: 4,
    parking: 3,
    area: 168,
    reference: "HM-1003",
    featured: true,
    description:
      "Apartamento com plantas amplas, varanda gourmet integrada e living em L. Prédio novo com lazer completo, spa, coworking e concierge.",
    images: [
      img("photo-1600607687939-ce8a6c25118c"),
      img("photo-1600566753086-00f18fb6b3ea"),
      img("photo-1600210492486-724fe5c67fb0"),
    ],
    features: ["Varanda gourmet", "Lazer completo", "Concierge", "Spa", "Coworking"],
  },
  {
    title: "Casa Térrea com Amplo Jardim",
    purpose: "venda",
    type: "casa",
    price: 1780000,
    city: "Campinas",
    neighborhood: "Nova Campinas",
    state: "SP",
    bedrooms: 3,
    suites: 1,
    bathrooms: 3,
    parking: 3,
    area: 260,
    reference: "HM-1004",
    featured: true,
    description:
      "Casa térrea arejada e iluminada, com jardim maduro, área gourmet coberta e ótima distribuição dos ambientes. Rua tranquila e arborizada.",
    images: [
      img("photo-1512917774080-9991f1c4c750"),
      img("photo-1600585154340-be6161a56a0c"),
      img("photo-1600566753190-17f0baa2a6c3"),
    ],
    features: ["Jardim", "Área gourmet", "Térrea", "Rua arborizada"],
  },
  {
    title: "Apartamento Garden com Quintal Privativo",
    purpose: "aluguel",
    type: "apartamento",
    price: 9800,
    city: "São Paulo",
    neighborhood: "Pinheiros",
    state: "SP",
    bedrooms: 2,
    suites: 1,
    bathrooms: 2,
    parking: 2,
    area: 110,
    reference: "HM-1005",
    featured: true,
    description:
      "Garden com quintal privativo perfeito para quem busca contato com o verde no coração da cidade. Mobiliado, pronto para morar, próximo a restaurantes e transporte.",
    images: [
      img("photo-1600566753086-00f18fb6b3ea"),
      img("photo-1600210492486-724fe5c67fb0"),
      img("photo-1600607687939-ce8a6c25118c"),
    ],
    features: ["Quintal privativo", "Mobiliado", "Pet friendly", "Próximo ao metrô"],
  },
  {
    title: "Casa de Alto Padrão à Beira-Mar",
    purpose: "venda",
    type: "casa",
    price: 6900000,
    city: "Guarujá",
    neighborhood: "Jardim Acapulco",
    state: "SP",
    bedrooms: 5,
    suites: 5,
    bathrooms: 6,
    parking: 6,
    area: 620,
    reference: "HM-1006",
    featured: true,
    description:
      "Mansão à beira-mar em condomínio exclusivo, com acesso privativo à praia, piscina de borda infinita e áreas de lazer completas. Vista deslumbrante para o oceano.",
    images: [
      img("photo-1600596542815-ffad4c1539a9"),
      img("photo-1600585154526-990dced4db0d"),
      img("photo-1600047509807-ba8f99d2cdde"),
      img("photo-1600566753190-17f0baa2a6c3"),
    ],
    features: ["Beira-mar", "Piscina infinita", "Acesso à praia", "Condomínio exclusivo"],
  },
  {
    title: "Apartamento Compacto Moderno",
    purpose: "aluguel",
    type: "apartamento",
    price: 4200,
    city: "São Paulo",
    neighborhood: "Itaim Bibi",
    state: "SP",
    bedrooms: 1,
    suites: 1,
    bathrooms: 1,
    parking: 1,
    area: 52,
    reference: "HM-1007",
    featured: false,
    description:
      "Studio moderno e funcional em localização premium, ideal para profissionais. Prédio com academia, lavanderia e rooftop.",
    images: [img("photo-1600210492486-724fe5c67fb0"), img("photo-1600566753086-00f18fb6b3ea")],
    features: ["Rooftop", "Academia", "Localização premium"],
  },
  {
    title: "Terreno Plano em Condomínio de Alto Padrão",
    purpose: "venda",
    type: "terreno",
    price: 980000,
    city: "Campinas",
    neighborhood: "Swiss Park",
    state: "SP",
    bedrooms: 0,
    suites: 0,
    bathrooms: 0,
    parking: 0,
    area: 600,
    reference: "HM-1008",
    featured: false,
    description:
      "Terreno plano e pronto para construir em condomínio consolidado, com infraestrutura completa e clube. Excelente topografia.",
    images: [img("photo-1500382017468-9049fed747ef"), img("photo-1449844908441-8829872d2607")],
    features: ["Plano", "Pronto para construir", "Condomínio consolidado"],
  },
  {
    title: "Sala Comercial em Torre Corporativa",
    purpose: "aluguel",
    type: "comercial",
    price: 12500,
    city: "São Paulo",
    neighborhood: "Faria Lima",
    state: "SP",
    bedrooms: 0,
    suites: 0,
    bathrooms: 2,
    parking: 3,
    area: 140,
    reference: "HM-1009",
    featured: false,
    description:
      "Conjunto comercial em torre AAA na Faria Lima, com laje ampla, vista privilegiada e infraestrutura completa. Certificação sustentável.",
    images: [img("photo-1497366754035-f200968a6e72"), img("photo-1497366811353-6870744d04b2")],
    features: ["Torre AAA", "Certificação verde", "Vista privilegiada"],
  },
  {
    title: "Apartamento Familiar Reformado",
    purpose: "venda",
    type: "apartamento",
    price: 1290000,
    city: "São Paulo",
    neighborhood: "Moema",
    state: "SP",
    bedrooms: 3,
    suites: 1,
    bathrooms: 2,
    parking: 2,
    area: 128,
    reference: "HM-1010",
    featured: false,
    description:
      "Apartamento totalmente reformado com bom gosto, ambientes integrados e ótima ventilação. Prédio com portaria 24h e lazer.",
    images: [img("photo-1600566753190-17f0baa2a6c3"), img("photo-1600585154526-990dced4db0d")],
    features: ["Reformado", "Portaria 24h", "Ambientes integrados"],
  },
];

async function seed() {
  console.log("Limpando tabela de imóveis...");
  await db.delete(schema.properties);
  console.log("Inserindo imóveis...");
  await db.insert(schema.properties).values(data);
  console.log(`✓ ${data.length} imóveis inseridos.`);
}

seed()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
